#!/bin/bash

# https://stackoverflow.com/questions/1146098/properly-handling-spaces-and-quotes-in-bash-completion
_overtake_complete_entries ()
{
  compopt -o filenames

  local IFS=$'\n'
  local prefix="${PASSWORD_STORE_DIR:-$HOME/.password-store/}"
  prefix="${prefix%/}/"
  #local cur="${COMP_WORDS[2]}"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local items=($(compgen -f $prefix$cur))

  for item in "${items[@]}"; do

    local name="${item#$prefix}"
    name="${name%.gpg}"

    # Skip hidden files
    [ "${name:0:1}" = "." ] && continue

    if [ -d "$item" ]; then
      COMPREPLY+=("$name/")
    else
      COMPREPLY+=("$name")
    fi
  done

  # Only add space to end if COMPREPLY option and it is a file, else disable this functionality(option)
  [[ ${#COMPREPLY[@]} -eq 1 && -f "$prefix${COMPREPLY[0]}.gpg" ]] || compopt -o nospace
}


command -v overtake &> /dev/null &&
_overtake_complete()
{
  local cur prev

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=( $(compgen -W "add copy delete edit recipients git help list show" -- $cur) )
  elif [ $COMP_CWORD -eq 2 ]; then
    case "$prev" in
      add|copy|delete|edit|show)
        # Complete *.gpg file paths
        _overtake_complete_entries
        ;;
      list)
        COMPREPLY=( $(compgen -W "--absolute --pretty" -- $cur) )
        ;;
      git)
        COMPREPLY=( $(compgen -W "--list-repositories --commit-all --pull-all" -- $cur) )
        ;;
      recipients)
        COMPREPLY=( $(compgen -W "--sync" -- $cur) )
        ;;
    esac
  fi

} &&
complete -F _overtake_complete overtake

